# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Huxh
subtitle: 
description:
keywords:
author: Hu Xiaohui
language: zh-CN
timezone:

# header-img: //o7bkkhiex.bkt.clouddn.com/lion-blur-bg.jpg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://huxhh.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:


# SNS settings
# RSS:
weibo_username: Huxhh
zhihu_username: hu-xiao-hui-69
github_username: Huxhh
twitter_username: StBarca
facebook_username:  
linkedin_username:  


# Sidebar settings
sidebar-about-description: DO OR DIE
sidebar-avatar: http://7xt4fa.com1.z0.glb.clouddn.com/newavater.jpeg    # use absolute URL



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# img CDN path
cdn-url: http://7xt4fa.com1.z0.glb.clouddn.com/ # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: ""

post-default-img: post-default.jpg

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Huxhh/Huxhh.github.io.git
  branch: master